{{- /* Secrets bootstrap — wire up to ExternalSecrets in production */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database-url: {{ if .Values.database.external.enabled }}{{ .Values.database.external.url }}{{ else }}postgresql://{{ .Values.database.postgresql.auth.username }}:{{ .Values.database.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.database.postgresql.auth.database }}{{ end }}
  redis-url: {{ if .Values.redis.external.enabled }}{{ .Values.redis.external.url }}{{ else }}redis://:{{ .Values.redis.redis.auth.password }}@{{ .Release.Name }}-redis-master:6379{{ end }}
  webhook-signing-key: {{ .Values.security.webhookSigningKey | quote }}
---
{{- if or .Values.channels.fcm.serviceAccountJson .Values.channels.sendgrid.apiKey .Values.channels.twilio.accountSid }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-channel-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.channels.fcm.serviceAccountJson }}
  fcm-service-account-json: {{ .Values.channels.fcm.serviceAccountJson | quote }}
  {{- end }}
  {{- if .Values.channels.sendgrid.apiKey }}
  sendgrid-api-key: {{ .Values.channels.sendgrid.apiKey | quote }}
  {{- end }}
  {{- if .Values.channels.twilio.accountSid }}
  twilio-auth-token: {{ .Values.channels.twilio.authToken | quote }}
  {{- end }}
{{- end }}
